### ISSUE TITLE
Unix wine launch

### ISSUE THREAD

**Issue by Polish-Civil** [blurite/rsprox#4]
https://github.com/blurite/rsprox/blob/22ef0c16dcecd11ea3decc9111aeb6a828f05cad/proxy/src/main/kotlin/net/rsprox/proxy/ProxyService.kt#L276

This will not work, the exe is expected to be an argument.

**Comment by Z-Kris** [comment]
👍 recently converted this from old-style Runtime.getRuntime().exec() to that, wasn't sure how it needed to change as I'm not too familiar with the new API for it. I don't use Linux so couldn't test it for myself. Shall be sorted in the near future.

**Comment by notmeta** [comment]
Fixed in https://github.com/blurite/rsprox/commit/374c4e8940f357c96acb37772b9e559568fefd49
